# Site settings
baseURL = "https://ijosh.com/"
languageCode = "en-US"
title = "Josh Vaughen"
theme = "split"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Copyright
copyright = "&copy;2024 Josh Vaughen"

[params]

  # Metadata for search engines and social sharing
  author = "Josh Vaughen"
  description = "Josh Vaughen is a machine learning engineer with a fierce passion for solo travel and fitness."
  shareImage = "images/profile.jpg"
  twitterHandle = "dvnll"

  # Favicon
  favicon = "images/favicon.png"

  [params.custom.css]
    enable = true
  
  [params.showemail]
    enable = true

  [params.showtwitter]
    enable = false

  [params.showlocation]
    enable = true

  [params.showemojis]
    enable = true

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/profile.jpg"
      position = "center center"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
